// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../../utilities";

// Export members:
export * from "./tcpingress";
export * from "./udpingress";

// Import resources to register:
import { TCPIngress } from "./tcpingress";
import { UDPIngress } from "./udpingress";

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "kubernetes:configuration.konghq.com/v1beta1:TCPIngress":
                return new TCPIngress(name, <any>undefined, { urn })
            case "kubernetes:configuration.konghq.com/v1beta1:UDPIngress":
                return new UDPIngress(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("crds", "configuration.konghq.com/v1beta1", _module)
