// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../../utilities";

import {ObjectMeta} from "../../meta/v1";

/**
 * KongConsumer is the Schema for the kongconsumers API
 */
export class KongConsumer extends pulumi.CustomResource {
    /**
     * Get an existing KongConsumer resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): KongConsumer {
        return new KongConsumer(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'kubernetes:configuration.konghq.com/v1:KongConsumer';

    /**
     * Returns true if the given object is an instance of KongConsumer.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is KongConsumer {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === KongConsumer.__pulumiType;
    }

    public readonly apiVersion!: pulumi.Output<"configuration.konghq.com/v1" | undefined>;
    /**
     * Credentials are references to secrets containing a credential to be provisioned in Kong.
     */
    public readonly credentials!: pulumi.Output<string[] | undefined>;
    /**
     * CustomID existing unique ID for the consumer - useful for mapping Kong with users in your existing database
     */
    public readonly custom_id!: pulumi.Output<string | undefined>;
    public readonly kind!: pulumi.Output<"KongConsumer" | undefined>;
    public readonly metadata!: pulumi.Output<ObjectMeta | undefined>;
    /**
     * Username unique username of the consumer.
     */
    public readonly username!: pulumi.Output<string | undefined>;

    /**
     * Create a KongConsumer resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: KongConsumerArgs, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            inputs["apiVersion"] = "configuration.konghq.com/v1";
            inputs["credentials"] = args ? args.credentials : undefined;
            inputs["custom_id"] = args ? args.custom_id : undefined;
            inputs["kind"] = "KongConsumer";
            inputs["metadata"] = args ? args.metadata : undefined;
            inputs["username"] = args ? args.username : undefined;
        } else {
            inputs["apiVersion"] = undefined /*out*/;
            inputs["credentials"] = undefined /*out*/;
            inputs["custom_id"] = undefined /*out*/;
            inputs["kind"] = undefined /*out*/;
            inputs["metadata"] = undefined /*out*/;
            inputs["username"] = undefined /*out*/;
        }
        if (!opts.version) {
            opts = pulumi.mergeOptions(opts, { version: utilities.getVersion()});
        }
        super(KongConsumer.__pulumiType, name, inputs, opts);
    }
}

/**
 * The set of arguments for constructing a KongConsumer resource.
 */
export interface KongConsumerArgs {
    readonly apiVersion?: pulumi.Input<"configuration.konghq.com/v1">;
    /**
     * Credentials are references to secrets containing a credential to be provisioned in Kong.
     */
    readonly credentials?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * CustomID existing unique ID for the consumer - useful for mapping Kong with users in your existing database
     */
    readonly custom_id?: pulumi.Input<string>;
    readonly kind?: pulumi.Input<"KongConsumer">;
    readonly metadata?: pulumi.Input<ObjectMeta>;
    /**
     * Username unique username of the consumer.
     */
    readonly username?: pulumi.Input<string>;
}
