// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../../types";
import * as utilities from "../../utilities";

import {ObjectMeta} from "../../meta/v1";

/**
 * KongIngress is the Schema for the kongingresses API
 */
export class KongIngress extends pulumi.CustomResource {
    /**
     * Get an existing KongIngress resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): KongIngress {
        return new KongIngress(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'kubernetes:configuration.konghq.com/v1:KongIngress';

    /**
     * Returns true if the given object is an instance of KongIngress.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is KongIngress {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === KongIngress.__pulumiType;
    }

    public readonly apiVersion!: pulumi.Output<"configuration.konghq.com/v1" | undefined>;
    public readonly kind!: pulumi.Output<"KongIngress" | undefined>;
    public readonly metadata!: pulumi.Output<ObjectMeta | undefined>;
    public readonly proxy!: pulumi.Output<outputs.configuration.v1.KongIngressProxy | undefined>;
    /**
     * Route represents a Route in Kong. Read https://getkong.org/docs/0.13.x/admin-api/#Route-object
     */
    public readonly route!: pulumi.Output<outputs.configuration.v1.KongIngressRoute | undefined>;
    /**
     * Upstream represents an Upstream in Kong.
     */
    public readonly upstream!: pulumi.Output<outputs.configuration.v1.KongIngressUpstream | undefined>;

    /**
     * Create a KongIngress resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: KongIngressArgs, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            inputs["apiVersion"] = "configuration.konghq.com/v1";
            inputs["kind"] = "KongIngress";
            inputs["metadata"] = args ? args.metadata : undefined;
            inputs["proxy"] = args ? args.proxy : undefined;
            inputs["route"] = args ? args.route : undefined;
            inputs["upstream"] = args ? args.upstream : undefined;
        } else {
            inputs["apiVersion"] = undefined /*out*/;
            inputs["kind"] = undefined /*out*/;
            inputs["metadata"] = undefined /*out*/;
            inputs["proxy"] = undefined /*out*/;
            inputs["route"] = undefined /*out*/;
            inputs["upstream"] = undefined /*out*/;
        }
        if (!opts.version) {
            opts = pulumi.mergeOptions(opts, { version: utilities.getVersion()});
        }
        super(KongIngress.__pulumiType, name, inputs, opts);
    }
}

/**
 * The set of arguments for constructing a KongIngress resource.
 */
export interface KongIngressArgs {
    readonly apiVersion?: pulumi.Input<"configuration.konghq.com/v1">;
    readonly kind?: pulumi.Input<"KongIngress">;
    readonly metadata?: pulumi.Input<ObjectMeta>;
    readonly proxy?: pulumi.Input<inputs.configuration.v1.KongIngressProxyArgs>;
    /**
     * Route represents a Route in Kong. Read https://getkong.org/docs/0.13.x/admin-api/#Route-object
     */
    readonly route?: pulumi.Input<inputs.configuration.v1.KongIngressRouteArgs>;
    /**
     * Upstream represents an Upstream in Kong.
     */
    readonly upstream?: pulumi.Input<inputs.configuration.v1.KongIngressUpstreamArgs>;
}
