// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../../types";
import * as utilities from "../../utilities";

import {ObjectMeta} from "../../meta/v1";

/**
 * KongClusterPlugin is the Schema for the kongclusterplugins API
 */
export class KongClusterPlugin extends pulumi.CustomResource {
    /**
     * Get an existing KongClusterPlugin resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): KongClusterPlugin {
        return new KongClusterPlugin(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'kubernetes:configuration.konghq.com/v1:KongClusterPlugin';

    /**
     * Returns true if the given object is an instance of KongClusterPlugin.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is KongClusterPlugin {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === KongClusterPlugin.__pulumiType;
    }

    public readonly apiVersion!: pulumi.Output<"configuration.konghq.com/v1" | undefined>;
    /**
     * Config contains the plugin configuration.
     */
    public readonly config!: pulumi.Output<{[key: string]: any} | undefined>;
    /**
     * ConfigFrom references a secret containing the plugin configuration.
     */
    public readonly configFrom!: pulumi.Output<outputs.configuration.v1.KongClusterPluginConfigFrom | undefined>;
    /**
     * ConsumerRef is a reference to a particular consumer
     */
    public readonly consumerRef!: pulumi.Output<string | undefined>;
    /**
     * Disabled set if the plugin is disabled or not
     */
    public readonly disabled!: pulumi.Output<boolean | undefined>;
    public readonly kind!: pulumi.Output<"KongClusterPlugin" | undefined>;
    public readonly metadata!: pulumi.Output<ObjectMeta | undefined>;
    /**
     * PluginName is the name of the plugin to which to apply the config
     */
    public readonly plugin!: pulumi.Output<string>;
    /**
     * Protocols configures plugin to run on requests received on specific protocols.
     */
    public readonly protocols!: pulumi.Output<string[] | undefined>;
    /**
     * RunOn configures the plugin to run on the first or the second or both nodes in case of a service mesh deployment.
     */
    public readonly run_on!: pulumi.Output<string | undefined>;

    /**
     * Create a KongClusterPlugin resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: KongClusterPluginArgs, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            inputs["apiVersion"] = "configuration.konghq.com/v1";
            inputs["config"] = args ? args.config : undefined;
            inputs["configFrom"] = args ? args.configFrom : undefined;
            inputs["consumerRef"] = args ? args.consumerRef : undefined;
            inputs["disabled"] = args ? args.disabled : undefined;
            inputs["kind"] = "KongClusterPlugin";
            inputs["metadata"] = args ? args.metadata : undefined;
            inputs["plugin"] = args ? args.plugin : undefined;
            inputs["protocols"] = args ? args.protocols : undefined;
            inputs["run_on"] = args ? args.run_on : undefined;
        } else {
            inputs["apiVersion"] = undefined /*out*/;
            inputs["config"] = undefined /*out*/;
            inputs["configFrom"] = undefined /*out*/;
            inputs["consumerRef"] = undefined /*out*/;
            inputs["disabled"] = undefined /*out*/;
            inputs["kind"] = undefined /*out*/;
            inputs["metadata"] = undefined /*out*/;
            inputs["plugin"] = undefined /*out*/;
            inputs["protocols"] = undefined /*out*/;
            inputs["run_on"] = undefined /*out*/;
        }
        if (!opts.version) {
            opts = pulumi.mergeOptions(opts, { version: utilities.getVersion()});
        }
        super(KongClusterPlugin.__pulumiType, name, inputs, opts);
    }
}

/**
 * The set of arguments for constructing a KongClusterPlugin resource.
 */
export interface KongClusterPluginArgs {
    readonly apiVersion?: pulumi.Input<"configuration.konghq.com/v1">;
    /**
     * Config contains the plugin configuration.
     */
    readonly config?: pulumi.Input<{[key: string]: any}>;
    /**
     * ConfigFrom references a secret containing the plugin configuration.
     */
    readonly configFrom?: pulumi.Input<inputs.configuration.v1.KongClusterPluginConfigFromArgs>;
    /**
     * ConsumerRef is a reference to a particular consumer
     */
    readonly consumerRef?: pulumi.Input<string>;
    /**
     * Disabled set if the plugin is disabled or not
     */
    readonly disabled?: pulumi.Input<boolean>;
    readonly kind?: pulumi.Input<"KongClusterPlugin">;
    readonly metadata?: pulumi.Input<ObjectMeta>;
    /**
     * PluginName is the name of the plugin to which to apply the config
     */
    readonly plugin?: pulumi.Input<string>;
    /**
     * Protocols configures plugin to run on requests received on specific protocols.
     */
    readonly protocols?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * RunOn configures the plugin to run on the first or the second or both nodes in case of a service mesh deployment.
     */
    readonly run_on?: pulumi.Input<string>;
}
